#!C:\Program Files (x86)\Python37-32\python.exe
print("Content-Type:text/HTML\n\r\n\r")
import cgi,cgitb
cgitb.enable()
form=cgi.FieldStorage()
nm=form.getvalue("name")
cno = form.getvalue("ContactNo")
addr=form.getvalue("addr")
bg=form.getvalue("bloodgroup")
import mysql.connector
con=mysql.connector.connect(host="localhost",user="root",password="",database="sushmitha")
cur=con.cursor()
cur.execute("insert into hosp values(%s,%s,%s,%s)",(nm,cno,addr,bg))
con.commit()
cur.close()
con.close()
print("<html>")
print("<head>")
print("<title>Blood Donation</title>")
print("</head>")
print("<body>")
print("<h3>Hospital Details added Successfully</h3>")
print("</br>")
print("</body>")
print("</html>")
