#!C:\Program Files (x86)\Python37-32\python.exe
print("Content-Type:text/HTML\n\r\n\r")
import cgi,cgitb
cgitb.enable()
form=cgi.FieldStorage()
nm=form.getvalue("name")
pd=form.getvalue("pwd")
g=form.getvalue("gender")
dob=form.getvalue("DOB")
cno = form.getvalue("ContactNo")
addr=form.getvalue("addr")
import mysql.connector
con=mysql.connector.connect(host="localhost",user="root",password="",database="sushmitha")
cur=con.cursor()
cur.execute("insert into UserRegister values(%s,%s,%s,%s,%s,%s)",(nm,pd,g,dob,cno,addr))
con.commit()
cur.close()
con.close()
print("<html>")
print("<head>")
print("<title>Blood Donation</title>")
print("</head>")
print("<body>")
print("<h3>User Profile Added Successfully</h3>")
print("</br>")
print("</body>")
print("</html>")
